-dontwarn org.**
-dontwarn kotlinx.datetime.**
-dontwarn com.microsoft.**
-keep class org.apache.logging.log4j.spi.StandardLevel{ *; }
-keep class org.apache.xmlbeans.**{ *; }
-keep class org.openxmlformats.**{ *; }
